package model.metier;
// Generated 25 f�vr. 2015 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auteurs generated by hbm2java
 */
@Entity
@Table(name="auteurs"
    ,catalog="librairie"
)
public class Auteurs extends Metier implements java.io.Serializable {


     private int idAuteur;
     private String nomAuteur;
     private String photo;
     private String site;
    

    public Auteurs() {
    }

	
    public Auteurs(int idAuteur, String nomAuteur) {
        this.idAuteur = idAuteur;
        this.nomAuteur = nomAuteur;
    }
    public Auteurs(int idAuteur, String nomAuteur, String photo, String site, Set livreses) {
       this.idAuteur = idAuteur;
       this.nomAuteur = nomAuteur;
       this.photo = photo;
       this.site = site;
    }
   
     @Id 

    
    @Column(name="id_auteur", unique=true, nullable=false)
    public int getIdAuteur() {
        return this.idAuteur;
    }
    
    public void setIdAuteur(int idAuteur) {
        this.idAuteur = idAuteur;
    }

    
    @Column(name="nom_auteur", nullable=false, length=50)
    public String getNomAuteur() {
        return this.nomAuteur;
    }
    
    public void setNomAuteur(String nomAuteur) {
        this.nomAuteur = nomAuteur;
    }

    
    @Column(name="photo", length=50)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="site", length=100)
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }





}


