package model.metier;
// Generated 25 f�vr. 2015 15:16:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cdes generated by hbm2java
 */
@Entity
@Table(name="cdes"
    ,catalog="librairie"
)
public class Cdes  implements java.io.Serializable {


     private int idCde;
     private Clients clients;
     private Date dateCde;
     private String etat;
     private float total;
     private Set ligcdeses = new HashSet(0);

    public Cdes() {
    }

	
    public Cdes(int idCde, Clients clients, Date dateCde, String etat, float total) {
        this.idCde = idCde;
        this.clients = clients;
        this.dateCde = dateCde;
        this.etat = etat;
        this.total = total;
    }
    public Cdes(int idCde, Clients clients, Date dateCde, String etat, float total, Set ligcdeses) {
       this.idCde = idCde;
       this.clients = clients;
       this.dateCde = dateCde;
       this.etat = etat;
       this.total = total;
       this.ligcdeses = ligcdeses;
    }
   
     @Id 

    
    @Column(name="id_cde", unique=true, nullable=false)
    public int getIdCde() {
        return this.idCde;
    }
    
    public void setIdCde(int idCde) {
        this.idCde = idCde;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_client", nullable=false)
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_cde", nullable=false, length=19)
    public Date getDateCde() {
        return this.dateCde;
    }
    
    public void setDateCde(Date dateCde) {
        this.dateCde = dateCde;
    }

    
    @Column(name="etat", nullable=false, length=50)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="total", nullable=false, precision=12, scale=0)
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }

}


