package model.metier;
// Generated 25 f�vr. 2015 15:16:10 by Hibernate Tools 4.3.1


import model.metier.Villes;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name="clients"
    ,catalog="librairie"
    , uniqueConstraints = {@UniqueConstraint(columnNames="e_mail"), @UniqueConstraint(columnNames="date_naissance")} 
)
public class Clients extends Metier implements java.io.Serializable {


     private int idClient;
     private Villes villes;
     private String nom;
     private String prenom;
     private String adresse;
     private String telephone;
     private String email;
     private String mdp;
     private Date dateNaissance;
     private String lectures;
     private String connuPar;
     private Integer newsLetter;
     private String qualite;
     private Set cdeses = new HashSet(0);

    public Clients() {
    }

	
    public Clients(int idClient, String nom, String EMail, String mdp) {
        this.idClient = idClient;
        this.nom = nom;
        this.email = EMail;
        this.mdp = mdp;
    }
    public Clients(int idClient, Villes villes, String nom, String prenom, String adresse, String telephone, String EMail, String mdp, Date dateNaissance, String lectures, String connuPar, Integer newsLetter, String qualite, Set cdeses) {
       this.idClient = idClient;
       this.villes = villes;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.telephone = telephone;
       this.email = EMail;
       this.mdp = mdp;
       this.dateNaissance = dateNaissance;
       this.lectures = lectures;
       this.connuPar = connuPar;
       this.newsLetter = newsLetter;
       this.qualite = qualite;
       this.cdeses = cdeses;
    }
   
     @Id 

    
    @Column(name="id_client", unique=true, nullable=false)
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cp")
    public Villes getVilles() {
        return this.villes;
    }
    
    public void setVilles(Villes villes) {
        this.villes = villes;
    }

    
    @Column(name="nom", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=50)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="adresse", length=100)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="telephone", length=14)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="e_mail", unique=true, nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mdp", nullable=false, length=50)
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_naissance", unique=true, length=10)
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    
    @Column(name="lectures", length=27)
    public String getLectures() {
        return this.lectures;
    }
    
    public void setLectures(String lectures) {
        this.lectures = lectures;
    }

    
    @Column(name="connu_par", length=9)
    public String getConnuPar() {
        return this.connuPar;
    }
    
    public void setConnuPar(String connuPar) {
        this.connuPar = connuPar;
    }

    
    @Column(name="news_letter")
    public Integer getNewsLetter() {
        return this.newsLetter;
    }
    
    public void setNewsLetter(Integer newsLetter) {
        this.newsLetter = newsLetter;
    }

    
    @Column(name="qualite", length=10)
    public String getQualite() {
        return this.qualite;
    }
    
    public void setQualite(String qualite) {
        this.qualite = qualite;
    }





}


