package model.metier;
// Generated 25 f�vr. 2015 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Editeurs generated by hbm2java
 */
@Entity
@Table(name="editeurs"
    ,catalog="librairie"
    , uniqueConstraints = @UniqueConstraint(columnNames="nom_editeur") 
)
public class Editeurs extends Metier implements java.io.Serializable {


     private int idEditeur;
     private String nomEditeur;
     private String site;
     private Set livreses = new HashSet(0);

    public Editeurs() {
    }

	
    public Editeurs(int idEditeur, String nomEditeur, String site) {
        this.idEditeur = idEditeur;
        this.nomEditeur = nomEditeur;
        this.site = site;
    }
    public Editeurs(int idEditeur, String nomEditeur, String site, Set livreses) {
       this.idEditeur = idEditeur;
       this.nomEditeur = nomEditeur;
       this.site = site;
       this.livreses = livreses;
    }
   
     @Id 

    
    @Column(name="id_editeur", unique=true, nullable=false)
    public int getIdEditeur() {
        return this.idEditeur;
    }
    
    public void setIdEditeur(int idEditeur) {
        this.idEditeur = idEditeur;
    }

    
    @Column(name="nom_editeur", unique=true, nullable=false, length=50)
    public String getNomEditeur() {
        return this.nomEditeur;
    }
    
    public void setNomEditeur(String nomEditeur) {
        this.nomEditeur = nomEditeur;
    }

    
    @Column(name="site", nullable=false, length=50)
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }





}


