package model.metier;
// Generated 25 f�vr. 2015 15:16:10 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ligcdes generated by hbm2java
 */
@Entity
@Table(name="ligcdes"
    ,catalog="librairie"
)
public class Ligcdes  implements java.io.Serializable {


     private LigcdesId id;
     private Cdes cdes;
     private Livres livres;
     private int qte;
     private Float montant;

    public Ligcdes() {
    }

	
    public Ligcdes(LigcdesId id, Cdes cdes, Livres livres, int qte) {
        this.id = id;
        this.cdes = cdes;
        this.livres = livres;
        this.qte = qte;
    }
    public Ligcdes(LigcdesId id, Cdes cdes, Livres livres, int qte, Float montant) {
       this.id = id;
       this.cdes = cdes;
       this.livres = livres;
       this.qte = qte;
       this.montant = montant;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCde", column=@Column(name="id_cde", nullable=false) ), 
        @AttributeOverride(name="idLivre", column=@Column(name="id_livre", nullable=false) ) } )
    public LigcdesId getId() {
        return this.id;
    }
    
    public void setId(LigcdesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cde", nullable=false, insertable=false, updatable=false)
    public Cdes getCdes() {
        return this.cdes;
    }
    
    public void setCdes(Cdes cdes) {
        this.cdes = cdes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_livre", nullable=false, insertable=false, updatable=false)
    public Livres getLivres() {
        return this.livres;
    }
    
    public void setLivres(Livres livres) {
        this.livres = livres;
    }

    
    @Column(name="qte", nullable=false)
    public int getQte() {
        return this.qte;
    }
    
    public void setQte(int qte) {
        this.qte = qte;
    }

    
    @Column(name="montant", precision=12, scale=0)
    public Float getMontant() {
        return this.montant;
    }
    
    public void setMontant(Float montant) {
        this.montant = montant;
    }




}


