package model.metier;
// Generated 25 f�vr. 2015 15:16:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LigcdesId generated by hbm2java
 */
@Embeddable
public class LigcdesId  implements java.io.Serializable {


     private int idCde;
     private int idLivre;

    public LigcdesId() {
    }

    public LigcdesId(int idCde, int idLivre) {
       this.idCde = idCde;
       this.idLivre = idLivre;
    }
   


    @Column(name="id_cde", nullable=false)
    public int getIdCde() {
        return this.idCde;
    }
    
    public void setIdCde(int idCde) {
        this.idCde = idCde;
    }


    @Column(name="id_livre", nullable=false)
    public int getIdLivre() {
        return this.idLivre;
    }
    
    public void setIdLivre(int idLivre) {
        this.idLivre = idLivre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LigcdesId) ) return false;
		 LigcdesId castOther = ( LigcdesId ) other; 
         
		 return (this.getIdCde()==castOther.getIdCde())
 && (this.getIdLivre()==castOther.getIdLivre());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCde();
         result = 37 * result + this.getIdLivre();
         return result;
   }   


}


