package model.metier;
// Generated 25 f�vr. 2015 15:16:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Livres generated by hbm2java
 */
@Entity
@Table(name="livres"
    ,catalog="librairie"
)
public class Livres extends Metier implements java.io.Serializable {


     private int idLivre;
     private Auteurs auteurs;
     private Editeurs editeurs;
     private String titre;
     private String annee;
     private String condense;
     private int nbPages;
     private float prix;
     private String couverture;
     private Set ligcdeses = new HashSet(0);

    public Livres() {
    }

	
    public Livres(int idLivre, Auteurs auteurs, Editeurs editeurs, String titre, String annee, String condense, int nbPages, float prix) {
        this.idLivre = idLivre;
        this.auteurs = auteurs;
        this.editeurs = editeurs;
        this.titre = titre;
        this.annee = annee;
        this.condense = condense;
        this.nbPages = nbPages;
        this.prix = prix;
    }
    public Livres(int idLivre, Auteurs auteurs, Editeurs editeurs, String titre, String annee, String condense, int nbPages, float prix, String couverture, Set ligcdeses) {
       this.idLivre = idLivre;
       this.auteurs = auteurs;
       this.editeurs = editeurs;
       this.titre = titre;
       this.annee = annee;
       this.condense = condense;
       this.nbPages = nbPages;
       this.prix = prix;
       this.couverture = couverture;
       this.ligcdeses = ligcdeses;
    }
   
     @Id 

    
    @Column(name="id_livre", unique=true, nullable=false)
    public int getIdLivre() {
        return this.idLivre;
    }
    
    public void setIdLivre(int idLivre) {
        this.idLivre = idLivre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_auteur", nullable=false)
    public Auteurs getAuteurs() {
        return this.auteurs;
    }
    
    public void setAuteurs(Auteurs auteurs) {
        this.auteurs = auteurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_editeur", nullable=false)
    public Editeurs getEditeurs() {
        return this.editeurs;
    }
    
    public void setEditeurs(Editeurs editeurs) {
        this.editeurs = editeurs;
    }

    
    @Column(name="titre", nullable=false, length=50)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="annee", nullable=false, length=4)
    public String getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(String annee) {
        this.annee = annee;
    }

    
    @Column(name="condense", nullable=false)
    public String getCondense() {
        return this.condense;
    }
    
    public void setCondense(String condense) {
        this.condense = condense;
    }

    
    @Column(name="nb_pages", nullable=false)
    public int getNbPages() {
        return this.nbPages;
    }
    
    public void setNbPages(int nbPages) {
        this.nbPages = nbPages;
    }

    
    @Column(name="prix", nullable=false, precision=12, scale=0)
    public float getPrix() {
        return this.prix;
    }
    
    public void setPrix(float prix) {
        this.prix = prix;
    }

    
    @Column(name="couverture", length=50)
    public String getCouverture() {
        return this.couverture;
    }
    
    public void setCouverture(String couverture) {
        this.couverture = couverture;
    }

}


