package model.metier;
// Generated 25 f�vr. 2015 15:16:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Villes generated by hbm2java
 */
@Entity
@Table(name = "villes", catalog = "librairie"
)
public class Villes extends Metier implements java.io.Serializable {

    private String cp;
    private String nomVille;
    private Set clientses = new HashSet(0);

    public Villes() {
    }

    public Villes(String cp, String nomVille) {
        this.cp = cp;
        this.nomVille = nomVille;
    }

    public Villes(String cp, String nomVille, Set clientses) {
        this.cp = cp;
        this.nomVille = nomVille;
        this.clientses = clientses;
    }

    @Id
    @Column(name = "cp", unique = true, nullable = false, length = 5)
    public String getCp() {
        return this.cp;
    }

    public void setCp(String cp) {
        this.cp = cp;
    }

    @Column(name = "nom_ville", nullable = false, length = 50)
    public String getNomVille() {
        return this.nomVille;
    }

    public void setNomVille(String nomVille) {
        this.nomVille = nomVille;
    }

   
}
